### ISSUE TITLE
Need example how to share data between mocks and scenario

### ISSUE THREAD

**Issue by fealaer** [unDemian/protractor-mock#1]
Hi there!

Is it possible to add example where we can see how to share data between mock and scenario? I can't find how to do it.

**Comment by unDemian** [comment]
Hey,
Did you check the `example.spec.coffee` file in the repo?

**Comment by fealaer** [comment]
Hi there!
Sorry for long response. Yes, of course I checked everything in this tiny project. Probably I was not clear in issue description.

I mean situation when I was needed to use the same data like in $httpBackend mocks on real page. For example:
I need to test login page. First of all, I create mock requests to http api and set up responses. After that, I would like to use the same data like in mocks in inputs on real page to test these scenarios, not define data again.

I hope now I am clear.

**Comment by unDemian** [comment]
Hi,
I understand now, the thing is that is very difficult to decouple the actual mocked data from the the protractor mock module, I will try to do this in a future version so that you can use the same data for e2e mocks, unit tests and inputs. I wil let this issue open as an enhancement.
Thanks for your feedback
I hope I can have some time soon to fix it, if you have any ideas you can create a pull request :)

**Comment by unDemian** [comment]
This project has been deprecated, please try using more low level npm packages for mocking. You can check the readme for some links.
Thanks
